In [ ]:
import requests
import bs4
from bs4 import BeautifulSoup

In [ ]:
def get_soup(url):
    responce=requests.get(url)
    html=responce.text
    soup = BeautifulSoup(html, 'html.parser')
    return soup

In [ ]:
website="https://www.btwonline.com/"
soup_site=get_soup(website)

In [ ]:
main_div=soup_site.find('div',attrs={'id':'NavigationTier2-4'})

In [ ]:
for i in main_div.find('li',attrs={'class':'navigation__item'}).find_all("a"):
    if i.attrs['href']!='#':
        print(i.text)
#     print(i.attrs['href'])

In [19]:
shirts="https://www.btwonline.com/collections/shirts?page=1"
shirts="https://www.btwonline.com/collections/t-shirts"

In [20]:
soup_shirt=get_soup(shirts)

In [21]:
def get_info(soup):
    flex=soup.find('div',attrs={'class':'product-list product-list--per-row-4 product-list--per-row-mob-2 product-list--per-row-mob-2 product-list--image-shape-portrait-23'})
    product_Info={"Name":[],"Prizes":[]}
    for info in flex.find_all('div',attrs={'class':'product-info'}):
        name=info.find('a').text.split("\n")[0]
        price=info.find('a').find('span').text.split('\n')[0]
        product_Info['Name'].append(name)
        product_Info['Prizes'].append(price)
    return pd.DataFrame(product_Info)

In [22]:
get_info(soup_shirt)

                            Name           Prizes
0                       LEAFLESS  Rs.1,490.00 PKR
1   OVERSIZE RELAXED FIT T-SHIRT  Rs.1,490.00 PKR
2   OVERSIZE RELAXED FIT T-SHIRT  Rs.1,490.00 PKR
3              Pull over t-shirt  Rs.2,690.00 PKR
4                          Sooty  Rs.1,690.00 PKR
5                          Ocean  Rs.1,690.00 PKR
6                 Endless Galaxy  Rs.1,690.00 PKR
7                          Chili  Rs.1,690.00 PKR
8                 Precious Pearl  Rs.1,990.00 PKR
9                      Dark Blue  Rs.1,790.00 PKR
10                   Ivory White  Rs.1,990.00 PKR
11                  Oyster White  Rs.1,690.00 PKR
12                       Captain  Rs.1,490.00 PKR
13                        Mirror  Rs.1,790.00 PKR
14                 Gochujang Red  Rs.1,490.00 PKR
15           Regular Fit T-Shirt  Rs.1,490.00 PKR
16           Regular Fit T-Shirt  Rs.1,490.00 PKR
17           Regular Fit T-Shirt  Rs.1,490.00 PKR
18           Regular Fit T-Shirt  Rs.1,490.00 PKR
19                    Ice Yellow  Rs.1,690.00 PKR
20                       Flowers  Rs.1,490.00 PKR
21                     Bumblebee  Rs.1,590.00 PKR
22                        Banana  Rs.1,490.00 PKR
23              For Give For Get  Rs.1,690.00 PKR

                            Name           Prizes
0                       LEAFLESS  Rs.1,490.00 PKR
1   OVERSIZE RELAXED FIT T-SHIRT  Rs.1,490.00 PKR
2   OVERSIZE RELAXED FIT T-SHIRT  Rs.1,490.00 PKR
3              Pull over t-shirt  Rs.2,690.00 PKR
4                          Sooty  Rs.1,690.00 PKR
5                          Ocean  Rs.1,690.00 PKR
6                 Endless Galaxy  Rs.1,690.00 PKR
7                          Chili  Rs.1,690.00 PKR
8                 Precious Pearl  Rs.1,990.00 PKR
9                      Dark Blue  Rs.1,790.00 PKR
10                   Ivory White  Rs.1,990.00 PKR
11                  Oyster White  Rs.1,690.00 PKR
12                       Captain  Rs.1,490.00 PKR
13                        Mirror  Rs.1,790.00 PKR
14                 Gochujang Red  Rs.1,490.00 PKR
15           Regular Fit T-Shirt  Rs.1,490.00 PKR
16           Regular Fit T-Shirt  Rs.1,490.00 PKR
17           Regular Fit T-Shirt  Rs.1,490.00 PKR
18           Regular Fit T-Shirt  Rs.1,490.00 PKR
19                    Ice Yellow  Rs.1,690.00 PKR
20                       Flowers  Rs.1,490.00 PKR
21                     Bumblebee  Rs.1,590.00 PKR
22                        Banana  Rs.1,490.00 PKR
23              For Give For Get  Rs.1,690.00 PKR

In [ ]:
# get_info